# Generated by Django 3.2.5 on 2021-08-30 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dockers', '0002_auto_20210822_0626'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
