# Generated by Django 3.2.5 on 2021-08-30 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dockers', '0004_auto_20210830_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dockers',
            name='CaseNo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='dockers',
            name='Host',
            field=models.CharField(max_length=100),
        ),
    ]
