# Generated by Django 3.2.5 on 2021-08-30 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dockers', '0005_auto_20210830_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dockers',
            name='Version',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='dockers',
            name='createdDate',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='dockers',
            name='expiryDate',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='dockers',
            name='region',
            field=models.CharField(max_length=50),
        ),
    ]
