# Generated by Django 3.2.5 on 2021-09-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dockers', '0006_auto_20210830_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.CharField(default='ISC', max_length=10),
            preserve_default=False,
        ),
    ]
