# Generated by Django 3.2.5 on 2021-09-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dockers', '0007_user_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='dockers',
            name='Note',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dockers',
            name='Visibilty',
            field=models.BooleanField(default=True),
        ),
    ]
