# Generated by Django 3.2.5 on 2021-09-15 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dockers', '0008_auto_20210915_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dockers',
            name='Note',
            field=models.TextField(max_length=200),
        ),
    ]
