# Generated by Django 3.2.5 on 2021-08-14 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ResourceLocator', '0004_delete_resource_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManageInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startCMD', models.CharField(max_length=30)),
                ('stopCMD', models.CharField(max_length=30)),
                ('ins', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ResourceLocator.instance')),
            ],
        ),
    ]
