# Generated by Django 3.2.5 on 2021-07-17 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HOST_NAME', models.CharField(max_length=50)),
                ('VERSION', models.CharField(max_length=50)),
                ('ADMIN_CONSOLE_PORT', models.IntegerField()),
                ('CATALOG_PORT', models.IntegerField()),
                ('LDM_Status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Resource_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(max_length=100)),
                ('provider_id', models.CharField(max_length=100)),
                ('Scanner_type', models.TextField(max_length=500)),
                ('Scanner_url', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Search_count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_count', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Resource_count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items_count', models.IntegerField()),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ResourceLocator.instance')),
                ('resource_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ResourceLocator.resource_type')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Resource_Name', models.CharField(max_length=100)),
                ('Owner', models.CharField(max_length=30)),
                ('Config', models.CharField(max_length=100)),
                ('createdTime', models.CharField(max_length=20)),
                ('modifiedTime', models.CharField(max_length=20)),
                ('MarkForDeletion', models.BooleanField(default=False)),
                ('Resource_Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ResourceLocator.resource_type')),
                ('ins', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ResourceLocator.instance')),
            ],
        ),
        migrations.CreateModel(
            name='application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_list', models.CharField(default='ResourceLocator', max_length=20)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applicationList', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
