# Generated by Django 3.2.5 on 2021-07-21 15:43

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ResourceLocator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource_type',
            name='Scanner_url',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
