# Generated by Django 3.2.5 on 2021-08-14 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ResourceLocator', '0003_resource_refresh_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resource_count',
        ),
    ]
