# Generated by Django 3.2.5 on 2021-08-23 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResourceLocator', '0004_delete_resource_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource_type',
            name='Scanner_type',
            field=models.BooleanField(),
        ),
    ]
