# Generated by Django 3.2.5 on 2021-08-23 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ResourceLocator', '0005_alter_resource_type_scanner_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource_type',
            name='Scanner_type',
        ),
    ]
