# Generated by Django 3.2.5 on 2021-08-23 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResourceLocator', '0006_remove_resource_type_scanner_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource_type',
            name='Scanner_type',
            field=models.BooleanField(default=False),
        ),
    ]
