# Generated by Django 3.2.5 on 2021-09-04 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResourceLocator', '0007_resource_type_scanner_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='REGION',
            field=models.CharField(default='ISC', max_length=10),
            preserve_default=False,
        ),
    ]
