# Generated by Django 3.2.5 on 2021-09-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResourceLocator', '0008_instance_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='PASSWORD',
            field=models.CharField(default='dummy', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instance',
            name='SECURITY_DOMAIN',
            field=models.CharField(default='dummy', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instance',
            name='USERNAME',
            field=models.CharField(default='dummy', max_length=20),
            preserve_default=False,
        ),
    ]
