# Generated by Django 3.2.5 on 2021-09-09 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ResourceLocator', '0010_application_apps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='apps',
        ),
    ]
