# Generated by Django 3.2.5 on 2021-09-10 12:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResourceLocator', '0011_remove_application_apps'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='apps',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=90), blank=True, default='{dummy}', size=None),
            preserve_default=False,
        ),
    ]
