# Generated by Django 3.2.5 on 2021-09-10 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ResourceLocator', '0012_application_apps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='application_list',
        ),
    ]
