# Generated by Django 3.2.5 on 2021-09-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResourceLocator', '0013_remove_application_application_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='Resource_Name',
            field=models.CharField(max_length=200),
        ),
    ]
