# Generated by Django 3.2.5 on 2021-09-12 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ResourceLocator', '0014_alter_resource_resource_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource_type',
            old_name='Scanner_type',
            new_name='MITI_Scanner',
        ),
        migrations.RenameField(
            model_name='resource_type',
            old_name='Scanner_url',
            new_name='Quick_Links',
        ),
    ]
